server:
  port: 8082

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    #ip-address: 192.168.3.38 #强制指定IP地址，默认会获取本机的IP地址
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/