# FROM zerofinance/devcontainer:20.04
# FROM registry.cn-shenzhen.aliyuncs.com/zerofinance/container:20.04
# FROM zerofinance/devcontainer:7
FROM registry.cn-shenzhen.aliyuncs.com/zerofinance/container:7
WORKDIR /Developer/workspace

USER dev
