# FROM zerofinance/devcontainer:20.04
# FROM registry.cn-shenzhen.aliyuncs.com/zerofinance/container:20.04
# FROM zerofinance/devcontainer:7
FROM registry.cn-shenzhen.aliyuncs.com/zerofinance/container:7
WORKDIR /workspaces

USER dev

#telepresence
# RUN sudo yum install torsocks sshfs conntrack python3 -y
# RUN git clone https://github.com/telepresenceio/telepresence.git /Developer/telepresence \
#     && cd /Developer/telepresence \
#     && sudo env PREFIX=/usr/local ./install.sh
