kind: Service
apiVersion: v1
metadata:
  name: springcloudk8sconfigdemo
  namespace: dave
  labels:
    app: springcloudk8sconfigdemo
    group: com.xwallet
    version: 0.0.1-SNAPSHOT
    provider: fabric8
spec:
  type: NodePort
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
    # nodePort: 30000
  selector:
    app: springcloudk8sconfigdemo
    group: com.xwallet
    version: 0.0.1-SNAPSHOT
    provider: fabric8