kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-service
  namespace: default
  labels:
    app: web-service
    group: com.xwallet
    version: 0.0.1-SNAPSHOT
    provider: fabric8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-service
      group: com.xwallet
      version: 0.0.1-SNAPSHOT
      provider: fabric8
  template:
    metadata:
      labels:
        app: web-service
        group: com.xwallet
        version: 0.0.1-SNAPSHOT
        provider: fabric8
    spec:
      containers:
      - name: web-service
        #image: registry.gcalls.cn/xwallet/web-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080