kind: Deployment
apiVersion: apps/v1
metadata:
  name: account-service
  namespace: default
  labels:
    app: account-service
    group: com.xwallet
    version: 0.0.1-SNAPSHOT
    provider: jkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
      group: com.xwallet
      version: 0.0.1-SNAPSHOT
      provider: jkube
  template:
    metadata:
      labels:
        app: account-service
        group: com.xwallet
        version: 0.0.1-SNAPSHOT
        provider: jkube
    spec:
      containers:
      - name: account-service
        # image: public-registry.zerofinance.cn/xwallet/account-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080