kind: ConfigMap
apiVersion: v1
metadata:
  name: springcloudk8sreloadconfigdemo
data:
  application.yml: |-
    greeting:
      message: Say Hello to the World
    farewell:
      message: Say Goodbye
    ---
    spring:
      profiles: dev
    greeting:
      message: Say Hello to the Developers
    farewell:
      message: Say Goodbye to the Developers
    ---
    spring:
      profiles: prod
    greeting:
      message: Say Hello to the Ops