spring:
  application:
    name: web-service

server:
  port: 8080

backend:
  ribbon:
    eureka:
      enabled: false
    client:
      enabled: true
    ServerListRefreshInterval: 5000

hystrix.command.BackendCall.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix.threadpool.BackendCallThread.coreSize: 5

#开启 Hystrix
feign:
  hystrix:
    enabled: true
    
#spring.cloud.kubernetes.loadbalancer.mode: SERVICE
spring.cloud.kubernetes.discovery.all-namespaces: true

    
#kubernetes.auth.tryKubeConfig: false
#spring.cloud.kubernetes.discovery.enabled: false
#spring.cloud.kubernetes.ribbon.enabled: false
#
#qotm:
#    ribbon:
#        listOfServers: qotm:5000
# account-service:
#    ribbon:
#        listOfServers: localhost:8081